#!/usr/bin/ruby
# Ruby front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.

v1 = ARGV[0]
output = `java -cp bin:lib/antlr-4.4-complete.jar frontend.Main #{v1}`; result = $?
result = result.to_s
exit_code = result.split(' ').last
if exit_code == "100"
	exit 100
elsif exit_code == "200"
    exit 200
end
